run_name: &run_name billsum-lgpt-3b-8192sl
gpu_type: a100_80gb
gpu_num: 8
platform: r1z1
image: mosaicml/pytorch:1.12.1_cu116-python3.9-ubuntu20.04
integrations:
  - integration_type: "wandb"
    project: &wandb_project lex-glue
    entity: mosaic-ml
  - integration_type: "git_repo"  # use local integration!
    git_repo: samhavens/m-lex-glue
    git_branch: main
# in the following command we download NLTK data to /usr/share/nltk_data which is the default location on Unix
# Rouge score calculation fails without it, so it is necessary for summarization evaluation 
command: >-
  set -e -x;
  cd m-lex-glue;
  pip install -r requirements.txt;
  python -c "import nltk;nltk.download('punkt')";
  composer task.py /mnt/config/parameters.yaml
optimization_level: 0
parameters:
  task: &task billsum
  max_seq_length: 8192
  model_type: mosaic
  model_name: &model_name legalgpt-3b
  tokenizer_name: &tokenizer_name sam-mosaic/pile-of-law-tokenizer
  # Run Name
  run_name: *run_name
  # Model
  model:
    name: *model_name
    use_pretrained: true
    pretrained_model_name: *model_name
    tokenizer_name: *tokenizer_name

  scheduler:
    name: linear_decay_with_warmup
    t_warmup: 0.08dur
    alpha_f: 0.2

  # haven't checked these values
  optimizer:
    name: decoupled_adamw
    lr: 1.0e-4
    betas:
      - 0.9
      - 0.98
    eps: 1.0e-06
    weight_decay: 1.0e-5 # Amount of weight decay regularization

  # again, untested
  max_duration: 10ep
  eval_interval: 1ep
  grad_clip_norm: -1.0

  global_train_batch_size: 32
  global_eval_batch_size: 32

  # System
  seed: 42
  grad_accum: auto
  precision: bf16
  # Logging
  progress_bar: true
  log_to_console: true
  callbacks:
    speed_monitor:
      window_size: 500
    lr_monitor: {}
  loggers:
    wandb: {}
  # Checkpoint to local filesystem or remote object store
  save_interval: 1ep
  save_num_checkpoints_to_keep: 1
  save_folder: s3://mosaicml-internal-checkpoints-shared/sam/lex-glue/${task}/${model_name}/${run_name}/checkpoints

  starting_checkpoint_load_path: s3://mosaicml-internal-checkpoints-shared/nlp/mmllllm/vitaliy/mmllllm-3b-8k-b1mt-tpol-tflashibi-VupRZm/checkpoints/ep0-ba51500-rank0.pt
  local_pretrain_checkpoints_folder: /tmp/checkpoints/lgtp-3b
