run_name: &run_name billsum-t03b-1024sl-32bs
gpu_type: a100_80gb
gpu_num: 8
platform: r1z1
image: mosaicml/composer:0.11.1
integrations:
  - integration_type: "wandb"
    project: &wandb_project lex-glue
    entity: mosaic-ml
  - integration_type: "git_repo"  # use local integration!
    git_repo: samhavens/m-lex-glue
    git_branch: main
command: >-
  set -e -x;
  cd m-lex-glue;
  pip install -r requirements.txt;
  python -c "import nltk;nltk.download('punkt')";
  composer task.py /mnt/config/parameters.yaml
optimization_level: 0
parameters:
  task: &task billsum
  max_seq_length: 1024
  model_name: &model_name bigscience/T0_3B
  tokenizer_name: &tokenizer_name bigscience/T0_3B
  # Run Name
  run_name: *run_name
  # Model
  model:
    name: *model_name
    use_pretrained: true
    pretrained_model_name: *model_name
    tokenizer_name: *tokenizer_name

  scheduler:
    name: linear_decay_with_warmup
    t_warmup: 0.08dur
    alpha_f: 0.2

  # haven't checked these values
  optimizer:
    name: decoupled_adamw
    lr: 3.0e-5  # 4x bs, so... almost 4x lr
    betas:
      - 0.9
      - 0.98
    eps: 1.0e-06
    weight_decay: 1.0e-5 # Amount of weight decay regularization

  # again, untested
  max_duration: 15ep
  eval_interval: 500ba # was 1ep, took too long
  grad_clip_norm: -1.0
  
  global_train_batch_size: 32  # big for regularizing, memorized too fast
  global_eval_batch_size: 8

  # System
  seed: 42
  grad_accum: auto
  precision: amp
  # Logging
  progress_bar: true
  log_to_console: true
  callbacks:
    speed_monitor:
      window_size: 500
    lr_monitor: {}
  loggers:
    wandb: {}
  # Checkpoint to local filesystem or remote object store
  save_interval: 1ep
  save_num_checkpoints_to_keep: 1
  save_folder: s3://mosaicml-internal-checkpoints-shared/sam/lex-glue/${task}/${model_name}/${run_name}/checkpoints
